### ISSUE TITLE
In the released version (NPM), package.json's main field needs to be updated to "dist/index.js"

### ISSUE THREAD

**Issue by Nickhoyer** [kravetsone/elysia-msgpack#1]
Currently after installing, it throws the error `Cannot find module 'elysia-msgpack' or its corresponding type declarations.ts(2307)
` whenever you try to import it

**Comment by kravetsone** [comment]
> Currently after installing, it throws the error `Cannot find module 'elysia-msgpack' or its corresponding type declarations.ts(2307) ` whenever you try to import it

I fixed it! Thanks for the Issue
