### ISSUE TITLE
Not working with requests

### ISSUE THREAD

**Issue by vadolasi** [kravetsone/elysia-msgpack#2]
When making a request where the content is msgpack, it returns error 422 (validation error). It seems like the parser is being executed after the validation.

**Comment by kravetsone** [comment]
> When making a request where the content is msgpack, it returns error 422 (validation error). It seems like the parser is being executed after the validation.

Sorry for the long answer! I didn't see the issue... But also I can't reproduce it.

**Comment by kravetsone** [comment]
I found bug and fix this issue)
